### ISSUE TITLE
Disable SSL Validation

### ISSUE THREAD

**Issue by carlskii** [stajkowski/webhooks#2]
Is it possible to add an attribute to disable SSL validation for testing? I'm currently using a self signed cert on my test server.

**Comment by stajkowski** [comment]
Absolutely, let me get this in today.

**Comment by stajkowski** [comment]
Complete, v1.2 posted on supermarket

**Comment by carlskii** [comment]
Hi there, just tried the v1.2 but I'm still getting the SSL validation error. I've added the new attribute to the example POST block.

**Comment by stajkowski** [comment]
Doing more testing.  I was able to replicate, fixing.

**Comment by stajkowski** [comment]
Verified fixed in v0.1.25

Let me know if you have any more issues.

**Comment by carlskii** [comment]
Hmm I'm still getting some issues here. i.e. 301 errors now. If I try a basic get in a browser it works OK.

```
Compiling Cookbooks...
Converging 1 resources
Recipe: webhooks::example
  * webhooks_request[Test Get HTTP Process] action get[2015-03-04T19:44:28+00:00] INFO: Processing webhooks_request[Test Get HTTP Process] action get (webhooks::example line 11)
[2015-03-04T19:44:28+00:00] INFO: Disabled SSL Validation.
[2015-03-04T19:44:28+00:00] INFO: Setting up request for https://172.16.28.200/vedsdk.
[2015-03-04T19:44:28+00:00] INFO: Setting up action get.
[2015-03-04T19:44:28+00:00] FATAL: Error encountered: Received an unexpected HTTP Response code 301..
================================================================================
    Error executing action `get` on resource 'webhooks_request[Test Get HTTP Process]'
    ================================================================================
    
    SystemExit
    ----------
    exit
    
    Cookbook Trace:
    ---------------
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:178:in `exit'
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:178:in `rescue in execute_request'
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:98:in `execute_request'
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:12:in `block (2 levels) in class_from_file'
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:10:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/recipes/example.rb
    
     11: webhooks_request "Test Get HTTP Process" do
     12:   uri "172.16.28.200/vedsdk"
     13:   ssl_validation false
     14:   use_ssl true
     15:   expected_response_codes [ 200, 201 ]
     16:   action :get
     17: end
     18: 
    
    Compiled Resource:
    ------------------
    # Declared in /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/recipes/example.rb:11:in `from_file'
    
    webhooks_request("Test Get HTTP Process") do
      action [:get]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :webhooks_request
      cookbook_name "webhooks"
      recipe_name "example"
      uri "172.16.28.200/vedsdk"
      use_ssl true
      expected_response_codes [200, 201]
      operation_name "Test Get HTTP Process"
      uri_port 80
      read_timeout 60
      save_response true
    end
    
[2015-03-04T19:44:28+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2015-03-04T19:44:28+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-03-04T19:44:28+00:00] ERROR: Exception handlers complete
[2015-03-04T19:44:28+00:00] FATAL: Stacktrace dumped to /Users/cbourne/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 2.998325 seconds
[2015-03-04T19:44:28+00:00] ERROR: webhooks_request[Test Get HTTP Process] (webhooks::example line 11) had an error: SystemExit: exit
[2015-03-04T19:44:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by stajkowski** [comment]
That's easy, you are getting a redirect.

Enable redirects by setting:

webhooks_request("Test Get HTTP Process") do
follow_redirect true
end

**Comment by carlskii** [comment]
Sorry !

Same again:

```
[2015-03-04T20:17:07+00:00] FATAL: Error encountered: Received an unexpected HTTP Response code 301..

    
    ================================================================================
    Error executing action `get` on resource 'webhooks_request[Test Get HTTP Process]'
    ================================================================================
    
    SystemExit
    ----------
    exit
    
    Cookbook Trace:
    ---------------
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:178:in `exit'
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:178:in `rescue in execute_request'
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:98:in `execute_request'
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:12:in `block (2 levels) in class_from_file'
    /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/providers/request.rb:10:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/recipes/example.rb
    
     10: webhooks_request "Test Get HTTP Process" do
     11:   uri "172.16.28.200/vedsdk"
     12:   ssl_validation false
     13:   use_ssl true
     14:   follow_redirect true
     15:   expected_response_codes [ 200, 201 ]
     16:   action :get
     17: end
     18: 
    
    Compiled Resource:
    ------------------
    # Declared in /Users/cbourne/.chef/local-mode-cache/cache/cookbooks/webhooks/recipes/example.rb:10:in `from_file'
```

**Comment by stajkowski** [comment]
What happens when you put this

expected_response_codes [ 200, 201, 301 ]

**Comment by carlskii** [comment]
This is what I get now. 

```
[2015-03-04T20:39:45+00:00] INFO: Webhooks Operation Successful: Test Get HTTP Process! Response Code 301.
[2015-03-04T20:39:45+00:00] INFO: Saving Response.
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://172.16.28.200/vedsdk/">here</a></body>
    - Completed GET of Test Get HTTP Process
[2015-03-04T20:39:45+00:00] WARN: Skipping final node save because override_runlist was given
[2015-03-04T20:39:45+00:00] INFO: Chef Run complete in 0.153402 seconds
[2015-03-04T20:39:45+00:00] INFO: Skipping removal of unused files from the cache
```

**Comment by stajkowski** [comment]
Ok change:

uri "172.16.28.200/vedsdk"

To:

uri "172.16.28.200/vedsdk/"

**Comment by carlskii** [comment]
OK that worked. So I think the `ssl_validation false` attributes working now. I'll do some more testing and let you know the outcome. Thanks for your assistance on this. Owe you three beers now :)

**Comment by stajkowski** [comment]
No problem man.  3 7&7's preferably lol.
